project_id = "vrbipcwunrlbfpumnroh"

[functions.flashscore-live]
verify_jwt = false

[functions.flashscore-today]
verify_jwt = false

[functions.sofascore-live]
verify_jwt = false

[functions.sofascore-today]
verify_jwt = false

[functions.fotmob-live]
verify_jwt = false

[functions.fotmob-today]
verify_jwt = false
